Complete hw1
stevensonmat2/frontend-homework pull request #1
Opened 2023-04-12 20:20 UTC by stevensonmat2

2023-04-13 23:39 UTC, vpetrova123 commented
Looks pretty good! Couple small styling suggestions to match the HW screenshot: round the corners of your container box, add some space between the "Enter a positive number" and "Is this a palindrome?" texts, and maybe change the output color from black to red when the number is negative.

2023-04-14 22:05 UTC, xuvea requested changes

2023-04-14 22:05 UTC, xuvea commented on hw1/02-palindrome.js
Small changes to add regarding quotes. The Airbnb JavaScript Style Guide says to use single quotes not double quotes for strings.

2023-04-17 00:06 UTC, stevensonmat2 commented on hw1/02-palindrome.js
thanks!

2023-04-17 00:08 UTC, merged